name = "shovel-worker"
type = "javascript"
zone_id = "52f3d88c8763dd5cd50989a430bfff56"
account_id = "c8526a45c47706d6c69f8d997004bd7a"
route = "shovel.aljb.dev/*"
compatibility_date = "2021-12-19"
kv_namespaces = [
    { binding = "SHOVEL", id = "cbe7991328f7412185a22c01de0ca271" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
